# base frontend
FROM node:latest

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY angular-src/package.json /usr/src/app
COPY angular-src/package-lock.json /usr/src/app
RUN npm install
COPY angular-src/. /usr/src/app

RUN $(npm bin)/ng build --prod --output-path=/public





